Iter5
OlesyaNovikova/metricsallert pull request #17
Opened 2023-06-11 16:55 UTC by OlesyaNovikova

2023-06-14 16:16 UTC, rktkov requested changes

2023-06-14 16:16 UTC, rktkov commented on internal/storage/storage.go
> +func (m *MemStorage) InitStorage() {
Зачем этот метод, если инициализация произошла в функции создания экземпляра хранилища - 16 строчка?

2023-06-14 16:16 UTC, rktkov commented on internal/storage/storage.go
> +	m.MemGauge[name] = gauge(value)
Нам ок, что возможна ситуация, что метрики с именем name не существует, и мы будем создавать новую запись в момент, когда хотим обновить существующую?

2023-06-14 16:16 UTC, rktkov commented on internal/storage/storage.go
> +			//value = strconv.FormatFloat(float64(val), 'f', 5, 64)
Не используемые код стоит удалят, а не комментировать.

2023-06-14 16:16 UTC, rktkov commented on internal/storage/storage.go
> +/*
см. комментарий выше

2023-06-14 16:16 UTC, rktkov commented on internal/handlers/handlers.go
> +type MemInterface interface {
Название интерфейса не отражает его суть

2023-06-14 16:16 UTC, rktkov commented on internal/handlers/handlers.go
> +var MemBase MemRepo
Почему у переменной глобальная область видимости. Кажется, что такого не должно быть.

2023-06-14 16:16 UTC, rktkov commented on cmd/server/main.go
> +	h "github.com/OlesyaNovikova/metricsallert.git/internal/handlers"
Возьмите в привычку сортировать импортируемые пакеты следующим образом:
1. пакеты стандартной библиотеки
2. внешние установленные пакеты
3. внутренние пакеты проекта

Для того, чтобы разные автоматические инструменты их не пересортировывали, разделяйте блоки пустой строкой.

см. комментарий про порядок импорта
https://stackoverflow.com/questions/24790175/when-is-the-init-function-run

2023-06-14 20:09 UTC, OlesyaNovikova commented on internal/storage/storage.go
> +	m.MemGauge[name] = gauge(value)
Да, по заданию запросы на добавление и обновление метрики на текущий момент идентичны, мы не знаем, что именно хотел клиент.

2023-06-14 21:47 UTC, OlesyaNovikova commented on internal/storage/storage.go
> +func (m *MemStorage) InitStorage() {
Остатки предыдущей реализации, убрала.

2023-06-15 07:08 UTC, rktkov approved these changes

2023-06-21 19:18 UTC, merged